spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://45.249.246.159:3306/test?characterEncoding=utf8&autoReconnect=true&useSSL=false
#    url: jdbc:mysql://106.53.145.136:3306/fly?characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/import_service?characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
#    password: root123#A

  ## 上传的文件大小设置
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB


##文件上传路径，root为根节点，location是具体路径,暂时先用Location全路径
upload:
  root: /App
  location: /App/upload

## 微信公众号配置
wechat:
  appid: wxfe820ab4d2e99546
  appsecret: 219e12880084c46d00c3637527be3d60
  token: wenguosheng
  aeskey: ZdNbXndyXvbf75SzRMEuCajc2hqAOu6NjPUQfkGWZ1e
  template_url: https://api.weixin.qq.com/cgi-bin/message/template/send?access_token=
  ##提示申请打包的订单受理成功
  apply_pack_id: 0byxomtbJhDmE99I62DELR-m9BZirTMZwpf9dhNz0gI
  ##提示付款模板id
  payment_id: NHcp767ZcTXawlw0jsxk-uzqiCFFs9DYc_kKplhhM8s
  ##待付款页面url
  payment_url: http://jiyun.flycloudstorage.com/client/jiyun/#/pages/mine/pending-payment/pending-payment
  ##提示申请打包id
  package_id: jNxy257o0oHsZxnOXqbI2iNPMrW5XQVAXuce_QpxLjI
  ##提示已发货id

  ## 拼团成员变更通知团长
  pin_type_chanage_id: a1rvB09yq2yikCmUoqZucwf_j1PJUcxFm3rjF9OEBkM

  ## 获取accessToken的地址
  access_token_url: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=SECRET
  ## 获取jsapi_ticket的地址
  jsapi_ticket_url: https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=ACCESS_TOKEN&type=jsapi
  ## 获取openid的地址
  openid_url: https://api.weixin.qq.com/sns/oauth2/access_token?appid=APPID&secret=APPSECRET&code=CODE&grant_type=authorization_code
  ## 获取用户基本信息的地址
  userinfo_url: https://api.weixin.qq.com/cgi-bin/user/info?access_token=ACCESS_TOKEN&openid=OPENID&lang=zh_CN
  ## 客户端的url
  url: jiyun.flycloudstorage.com:8622

logging:
  level:
    # 关闭其它软件的日志，减少干扰
    #org: ERROR
    #net: ERROR
    #com: ERROR
    # 开启MySQL JDBC驱动的日志
    MySQL: DEBUG
    #开启数据库语句打印
    com.dwgj.mlxydedicatedline.mapper: DEBUG

mybatis:
  mapper-locations: classpath*:com/dwgj/mlxydedicatedline/mapper/*Mapper.xml
    # SQL语句打印
    #configuration:
  #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8622
  ## 部署的服务器域名
  host: 106.53.145.136
  ## 部署的域名
  domain: http://106.53.145.136
  ## 前缀
  prefix: http://
  url: jiyun.flycloudstorage.com

## 微信公众号配置
#wechat:
#  appid: wxe511fc8b399774a4
#  appsecret: f0e4150f85cfc1909a31afa6d5de58d9
#  token: wenguosheng
#  aeskey: ZdNbXndyXvbf75SzRMEuCajc2hqAOu6NjPUQfkGWZ1e
#  template_url: https://api.weixin.qq.com/cgi-bin/message/template/send?access_token=
#  ##提示申请打包的订单受理成功
#  apply_pack_id: 0byxomtbJhDmE99I62DELR-m9BZirTMZwpf9dhNz0gI
#  ##提示付款模板id
#  payment_id: 8sw5t_D5pHllMugR73YVM90LQ85wpqbdppDQBo1Lgg8
#  ##待付款页面url
#  payment_url: http://www.wennever.cn/jiyun/#/pages/mine/pending-payment/pending-payment
#  ##提示申请打包id
#  package_id: jNxy257o0oHsZxnOXqbI2iNPMrW5XQVAXuce_QpxLjI
#  ##提示已发货id
#
#  ## 拼团成员变更通知团长
#  pin_type_chanage_id: tQu7PrroZqLqC2bmGEiNA9LGa5d_u5twHXlckSm2Z7o
#
#  ## 获取accessToken的地址
#  access_token_url: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=SECRET
#  ## 获取jsapi_ticket的地址
#  jsapi_ticket_url: https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=ACCESS_TOKEN&type=jsapi
#  ## 获取openid的地址
#  openid_url: https://api.weixin.qq.com/sns/oauth2/access_token?appid=APPID&secret=APPSECRET&code=CODE&grant_type=authorization_code
#  ## 获取用户基本信息的地址
#  userinfo_url: https://api.weixin.qq.com/cgi-bin/user/info?access_token=ACCESS_TOKEN&openid=OPENID&lang=zh_CN
#  ## 客户端的url
#  url: www.wennever.cn:8692
#
#logging:
#    level:
#        # 关闭其它软件的日志，减少干扰
#        #org: ERROR
#        #net: ERROR
#        #com: ERROR
#        # 开启MySQL JDBC驱动的日志
#        MySQL: DEBUG
#        #开启数据库语句打印
#        com.dwgj.mlxydedicatedline.mapper: DEBUG
#
#mybatis:
#  mapper-locations: classpath*:com/dwgj/mlxydedicatedline/mapper/*Mapper.xml
#  # SQL语句打印
#  #configuration:
#     #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#server:
#  port: 8693
#  ## 部署的服务器域名
#  host: 106.53.145.136
#  ## 部署的域名
#  domain: http://106.53.145.136
#  ## 前缀
#  prefix: http://
