spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://106.53.145.136:3306/fly?characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://45.249.246.159:3306/test?characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/import_service?characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://106.53.93.90:3306/import_service?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=true&allowMultiQueries=true
    username: root
    password: root
#    password: root123#A
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
  profiles:
    include: druidStat

  http:

  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
    ## 下面临时路径为了解决上传文件的时候OS系统自动删除临时目录的
  servlet:
    multipart:
      location: /App/upload/tmp

logging:
  level:
    # 关闭其它软件的日志，减少干扰
    #org: ERROR
    #net: ERROR
    #com: ERROR
    # 开启MySQL JDBC驱动的日志
    MySQL: DEBUG
    #开启数据库语句打印
    com.example.warehouse.mapper: DEBUG
mybatis:
  mapper-locations: classpath*:com/example/warehouse/mapper/*Mapper.xml
server:
  port: 8620
  domain: 106.53.145.136
  client-url: jiyun.flycloudstorage.com
  servlet:
    context-path: /api
    #  port: 10569

##文件上传路径，root为根节点，location是具体路径,暂时先用Location全路径
upload:
  root: /App
  location: /App/upload

## 邮件配置信息
mail:
  sender-address: 978771653@qq.com
  sender-name: 飞轮国际云仓物流科技有限公司
  authorization-code: vpxppiiziagxbcba

## 腾讯云对象存储配置
tencent:
#  正式腾讯云对象存储
  appid: 1253561272
  secret-id: AKIDDF0VjgLksjIacvxhBOKyMTJs9AuNZU9X
  secret-key: 80buwhBOO7amgJfkY5LL3UfZCXbOu97n
  #存储对象桶名称
  bucket-name: flycloud

## 微信公众号配置
wechat:
  appid: wxfe820ab4d2e99546
  appsecret: 219e12880084c46d00c3637527be3d60
  token: wenguosheng
  aeskey: ZdNbXndyXvbf75SzRMEuCajc2hqAOu6NjPUQfkGWZ1e
  template_url: https://api.weixin.qq.com/cgi-bin/message/template/send?access_token=
  ## 包裹仓储即将到期，提醒发货通知
  goods_overtime: ZItrwqAESGTaBi9wwkpZilF7P81QcxFFZ46vwBO9Nt4
  ##提示申请打包的订单受理成功
  apply_pack_id: 0byxomtbJhDmE99I62DELR-m9BZirTMZwpf9dhNz0gI
  ##提示付款模板id
  payment_id: NHcp767ZcTXawlw0jsxk-uzqiCFFs9DYc_kKplhhM8s
  ##待付款页面url
  payment_url: http://jiyun.flycloudstorage.com/client/jiyun/#/pages/mine/pending-payment/pending-payment
  ##提示申请打包id
  package_id: jNxy257o0oHsZxnOXqbI2iNPMrW5XQVAXuce_QpxLjI
  ##提示已发货id

  ## 评价售后处理
  after_sales: pAeRqerngvWUPzwkuDy5tAFNKQhf7eEXgNoFdwDoYDo
  ## 提示充值成功的id
  topup_success_id: 5kVqlca7W_dARvgOei-H7TXmjZVCHUx5Z3K8p1mOR54
  ## 入库通知
  pacakge_in_id: KsLbkMjm8l9b8zaaQJKzFK--s_eb0rviqCa78gWW80w
  ## 入库详情-申请打包页面
  package_pack_url: http://jiyun.flycloudstorage.com/client/jiyun/#/pages/mine/application-package/application-package
  ## 拼团成员变更通知团长
  pin_type_chanage_id: a1rvB09yq2yikCmUoqZucwf_j1PJUcxFm3rjF9OEBkM
  ## 拼团审核详情路径
  pin_detail_url: http://jiyun.flycloudstorage.com/jiyun/#/pages/mine/pending-payment/pending-payment

  ## 获取accessToken的地址
  access_token_url: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=SECRET
  ## 获取jsapi_ticket的地址
  jsapi_ticket_url: https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=ACCESS_TOKEN&type=jsapi
  ## 获取openid的地址
  openid_url: https://api.weixin.qq.com/sns/oauth2/access_token?appid=APPID&secret=APPSECRET&code=CODE&grant_type=authorization_code
  ## 获取用户基本信息的地址
  userinfo_url: https://api.weixin.qq.com/cgi-bin/user/info?access_token=ACCESS_TOKEN&openid=OPENID&lang=zh_CN
  ## 客户端的url
  url: jiyun.flycloudstorage.com:8622
  ## 公众号名称
  name: 飞轮国际
  ## 仓库名称
  warehouse_name: 飞轮国际6号仓
  ## 订单号开头
  order_type: FL
  ## 轨迹详情路径
  trajectory_url: http://jiyun.flycloudstorage.com/client/jiyun/#/pages/mine/waiting-to-receive/trajectory/trajectory
  ## 轨迹更新通知接口地址
  tracking-update-url: /api/AppDataService/trackingUpdateMessage
  system_code: FLY
track-17-token: 222A6BF48A22A49560FAE95202B22969

  ##测试的公众号
  #appid:wxe511fc8b399774a4
  #secret:f0e4150f85cfc1909a31afa6d5de58d9
## 微信公众号配置
#wechat:
#  appid: wxe511fc8b399774a4
#  appsecret: f0e4150f85cfc1909a31afa6d5de58d9
#  token: wenguosheng
#  aeskey: ZdNbXndyXvbf75SzRMEuCajc2hqAOu6NjPUQfkGWZ1e
#  template_url: https://api.weixin.qq.com/cgi-bin/message/template/send?access_token=
#  ##提示付款模板id
#  payment_id: 8sw5t_D5pHllMugR73YVM90LQ85wpqbdppDQBo1Lgg8
#  ##待付款页面url
#  payment_url: http://testmy.flycloudstorage.com/client/jiyun/#/pages/mine/pending-payment/pending-payment
#  ##提示申请打包id
#  package_id: jNxy257o0oHsZxnOXqbI2iNPMrW5XQVAXuce_QpxLjI
#  ##提示已发货id
#
#  ## 入库通知
#  pacakge_in_id: BzvaoLCkWKEiV9vF5XCe41U-utBMdb2y38q1fbOFDvY
#  ## 入库详情-申请打包页面
#  package_pack_url: http://testmy.flycloudstorage.com/client/jiyun/#/pages/mine/application-package/application-package
#  ## 拼团成员变更通知团长
#  pin_type_chanage_id: tQu7PrroZqLqC2bmGEiNA9LGa5d_u5twHXlckSm2Z7o
#  ## 拼团审核详情路径
#  pin_detail_url: http://testmy.flycloudstorage.com/jiyun/#/pages/mine/pending-payment/pending-payment
#
#  ## 获取accessToken的地址
#  access_token_url: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=SECRET
#  ## 获取jsapi_ticket的地址
#  jsapi_ticket_url: https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=ACCESS_TOKEN&type=jsapi
#  ## 获取openid的地址
#  openid_url: https://api.weixin.qq.com/sns/oauth2/access_token?appid=APPID&secret=APPSECRET&code=CODE&grant_type=authorization_code
#  ## 获取用户基本信息的地址
#  userinfo_url: https://api.weixin.qq.com/cgi-bin/user/info?access_token=ACCESS_TOKEN&openid=OPENID&lang=zh_CN
#  ## 客户端的url
#  url: testmy.flycloudstorage.com:9622
#  ## 公众号名称
#  name: 飞轮国际

